# Generated by Django 4.2.6 on 2023-10-07 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TestTable',
            fields=[
                ('report_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('report_type', models.TextField(null=True)),
            ],
            options={
                'db_table': 'report_type',
            },
        ),
    ]
