# Generated by Django 4.2.6 on 2023-10-07 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Drawings',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('school', models.CharField(max_length=20, null=True)),
                ('created_by', models.CharField(max_length=20, null=True)),
                ('creative_url', models.TextField(null=True)),
                ('is_active', models.BooleanField(null=True)),
                ('created_on', models.DateTimeField(null=True)),
                ('modified_on', models.DateTimeField(null=True)),
            ],
            options={
                'db_table': 'drawings',
            },
        ),
    ]
