# Generated by Django 3.2 on 2024-01-29 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='drawings',
            name='subject',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='drawings',
            name='use_ai',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
