# Generated by Django 4.2.6 on 2023-10-07 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_nonprofits'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drawings',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='drawings',
            name='modified_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='nonprofits',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='nonprofits',
            name='modified_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
