# Generated by Django 3.2 on 2024-01-30 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20240130_0229'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='current_sponsors',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='books',
            name='total_sponsors',
            field=models.IntegerField(default=1, null=True),
        ),
    ]
