# Generated by Django 3.2 on 2024-02-01 23:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_sponsors_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='SponsoredBooks',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.IntegerField(null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('book_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='api.books')),
                ('sponsor_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='api.sponsors')),
            ],
            options={
                'db_table': 'sponsor_books',
            },
        ),
    ]
