# Generated by Django 3.2 on 2024-02-19 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_sponsoredbooks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drawings',
            name='created_by',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='drawings',
            name='school',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sponsoredbooks',
            name='amount',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
